### ISSUE TITLE
Time Central

### ISSUE THREAD

**Issue by slinstj** [code-on-yii/definicoes#1]
Primeiro, veja o contexto deste issue nesta discussão do grupo Yii Framework Brasil (https://groups.google.com/forum/#!topic/yii-framework-brasil/9GR67Fo90-8)

Definição do time central e sua expansão através da votação dos membros conforme forem entrando no time. Somente após esta definição abriremos outros issues para definir objetivos em conjunto.

Deseja participar? Mostre seu(s) trabalho(s) e seus argumentos abaixo. Um time ativo e disciplinado pode ser melhor do que um time de gurus congelado! 

Seja bem-vindo!

**Comment by newerton** [comment]
:+1: 

Gostaria de fazer parte do time central, tenho algumas funções que pode adiantar algumas novas extensões para o Yii.

**Comment by slinstj** [comment]
Já faz!  Bem-vindo @newerton! Agora poderá me ajudar a decidir os próximos que solicitarem. Acredito que mais 3 ou 4 membros talvez sejam suficientes. O que acha?

**Comment by ericmaicon** [comment]
:+1:

Gostaria de fazer parte também. Consigo ajudar nos widgets e aprender no que der e vier

**Comment by almirb** [comment]
Olá pessoal!

Também gostaria de fazer parte do grupo! Lá vai uma breve descrição:
Trabalho com o Yii desde agosto de 2014.  Tenho 3 projetos desenvolvidos em Yii1 e 2 projetos (iniciando o terceiro agora) em Yii2. Não tenho muita prática com criação de widgets, mas creio que isso não seja um problema.  Recentemente trabalhei na customização de uma variante do Gii (enhanced-gii) juntamente com meu amigo Iuri, adaptando-o às minhas necessidades.  Sou fã do Kartik e gosto de utilizar seus componentes (ao menos a Grid, o DateControl e o Select2).

Algo que facilitaria muito nosso trabalho seria um catálogo centralizado de widgets (além dos desenvolvidos na própria comunidade).  A gama de widgets, behaviors, etc do Yii é bem extensa e, na maioria das vezes, já existe algo que supre nossas necessidades.

**Comment by slinstj** [comment]
Ótimo Eric e Almir, sou a favor de os dois participarem. Vamos aguardar a opinião do @newerton. Depois que tivermos um time formado vamos discutir como será a participação (em relação ao tempo que será dedicado) mas claro, dentro das condições de cada um, desde que não fique muito abaixo do que for considerado coletivamente como razoável.

**Comment by newerton** [comment]
@almirb acho válido esse catálogo de widgets, até por que tem muitos widgets excelente que supri muitas as necessidades com 1 objetivo.

Convida também o [@wbraganca](https://github.com/wbraganca), ele criou alguns widgets que uso, e me ajuda muito.

**Comment by slinstj** [comment]
@newerton, faltou seu posicionamento, se também está de acordo com a entrada de ambos.

**Comment by newerton** [comment]
@slinstj estou de acordo sim, ambos veio para somar, e com certeza conseguiremos bons resultados e bons projetos neste grupo.

**Comment by slinstj** [comment]
Fechado! Então estou adicionando os dois... sejam bem-vindos!

**Comment by slinstj** [comment]
@almirb e @ericmaicon já mandei os convites. Assim que aceitarem podemos começar algumas novas discussões.

**Comment by almirb** [comment]
Convite aceito.

**Comment by leandrogehlen** [comment]
Olá, boa tarde! 
Agradeço o convite, e estou disposto a colaborar. Trabalho com yii desde 2009 e contribuo e já desenvolvi algumas das extensões que se pretente desenvolver. sou Proprietário da organização
[YiiBrasil](https://github.com/yiibr)

**Comment by ericmaicon** [comment]
Bem vindo @leandrogehlen , bela organization.

@slinstj algo para falar?

**Comment by slinstj** [comment]
Claro, inclusive o convite foi meu. Fico feliz que tenha aceitado, @leandrogehlen. Meu voto é a favor. Com mais um voto você está dentro! Vamos esperar os demais.

**Comment by almirb** [comment]
Então seja bem-vindo @leandrogehlen!

**Comment by slinstj** [comment]
Fechou, @leandrogehlen está no time. Mais uma vez seja bem-vindo! (Vou te add em alguns minutos)

**Comment by slinstj** [comment]
@Yii-Brasil-Dev/core sou a favor de fecharmos nessa quantidade de 5 membros. Talvez possamos adicionar outros mais pra frente. Acho que, por hora, mais do que isso pode começar a tornar difícil o gerenciamento pra nós mesmos. Se tivermos maioria nesse sentido, podem fechar este issue também.

**Comment by slinstj** [comment]
@leandrogehlen falta você aceitar o convite pro time (e também pro slack). :+1:

**Comment by phmiranda** [comment]
Bom dia, com faço para participar da organization e contribuir de alguma forma com a comunidade ?

**Comment by slinstj** [comment]
@phmiranda, obrigado pelo seu interesse. No entanto, o grupo não decolou como esperado. Todos acabamos tendo muitos contratempos. Abraço!
