### ISSUE TITLE
Sobre a dinâmica do time

### ISSUE THREAD

**Issue by slinstj** [code-on-yii/definicoes#3]
Esse é um ponto importante. 

Ao meu ver, seria interessante que cada membro liderasse pelo menos um projeto, por mais simples que ele seja. Acho que a seguinte ordem seria um bom começo:

1. Iniciar um tópico aqui (ou em outra ferramenta conforme definida no issue #2) para discutir a viabilidade e real utilidade do projeto;
2. Se a maioria considerar que vale à pena, quem sugeriu (de preferência!) deve iniciar o projeto (repositório) e dar o pontapé inicial;
3. A partir disso, os demais deveriam obrigatoriamente "forkar" o repositório e ajudar em uma ou várias áreas, ou seja, ser participativos (apoio moral faz o time) com sugestões, correções, propor melhorias no código, criar ou melhorar os @docblocks, criar testes, sugerir e implementar novas features, etc;

Gostaria de ouvir o @Yii-Brasil-Dev/core aqui também.

**Comment by ericmaicon** [comment]
Acho legal, só acho q antes disso ou durante, devemos também definir o padrão que vamos seguir:
1. Tudo testado
2. Bem documentado
3. SemVer
4. Português? Inglês?
5. Iremos usar Travis?
6. Seguir PSRs?

**Comment by newerton** [comment]
@ericmaicon pontos legais para discutirmos.

Eu acho bom, pelo menos o código e documentação em inglês, já peguei bastante código de outros paises, e por sorte estavam documentados em inglês, caso faça-mos projetos para a demanda regional, temos que ter em mente que outros usuários de outros países irão usar também.

Caso haja alguma Issue em inglês, podemos responder em inglês, como acontece habitualmente pelo GitHub.

Travis nunca trabalhei, e gostaria de trabalhar, iremos crescer profissionalmente não só no Yii, mais o universo de cooperativismo.

Podemos listar quais projetos iremos desenvolver, ver a necessidade dele, ou até mesmo pegar algum projeto pronto, e melhorar ao nosso ponto de vista.

**Comment by slinstj** [comment]
Eric, poderia abrir um novo issue para discutirmos isso? Talvez "Padrões de código" ou algo a teu critério. Acho muito válido. E aqui podemos discurtir a questão de como será o pontapé inicial de cada projeto. O que acham?

**Comment by almirb** [comment]
Um item importante seria o uso (ou não) de widgets de terceiros para a elaboração destes projetos.  Já trabalhei com  pessoas que usavam widgets para quase tudo e também pessoas que evitavam utilizá-los para manter o código o menos dependente possível.  Talvez poderíamos utilizá-los com parcimônia.

**Comment by slinstj** [comment]
@almirb, acho uma preocupação válida mas acredito pode ser analisada e discutida por projeto. A ideia aqui seria mais pegar as linhas gerais que queremos seguir para todos os projetos para que tenhamos um norte e possamos começar a codificar o quanto antes.

**Comment by leandrogehlen** [comment]
Acredito que atualmente, é impossível trabalhar sem testes, e o travis é fácil de utilizar.
Além disso também acho muito importante utilizar o [https://scrutinizer-ci.com/](https://scrutinizer-ci.com/), pois avalia qualidade do codigo e quanto este codigo esta coberto por testes

**Comment by slinstj** [comment]
Pessoal, acho que perdemos o foco deste tópico. Podemos discurtir esses aspectos técnicos no #4 e deixar este tópico para definir mais a dinâmica do time. Posso tomar a liberdade de remover as mensagens não relacionadas?

**Comment by slinstj** [comment]
@code-on-yii/core bump!

**Comment by slinstj** [comment]
Um outra ideia (comentei no slack) seria a seguinte:

Cada membro teria uma meta de iniciar pelo menos um projeto, mesmo que simples (um validador, um widget, uma extension, etc) na organização e então os demais apoiariam...
OU
Poderia ceder um (ou mais) de seus projetos para o grupo trabalhar nele. 

Imagine, só aí seriam 5 projetos, no mínimo, para serem aprimorados e melhorados. Claro que a cessão seria com os devidos créditos, tipo: criador: fulano e os que ajudarem vão colocando seus nomes no próprio código (métodos, etc) conforme o caso (@author).

E por fim, em caso de saída do membro por qualquer que seja o motivo, ele pode levar o projeto de volta para seu id e o grupo fica com um fork ou cria um fork independente.

@code-on-yii/core ?

**Comment by ericmaicon** [comment]
Só acho que não precisa do lance de retornar o projeto para o id. Fica complicado já tudo tá vinculado aqui e trocar de tds q usam é paia. (trocar namespace, composer, ...). Por mim, se eu sair, deixo tudo aqui mesmo.

**Comment by slinstj** [comment]
É isso aí, precisamos de ideias mesmo. Acho válida sua sugestão.

**Comment by almirb** [comment]
Realmente não tem motivo do projeto retornar ao id.  Concordo com as demais colocações... vamos criar projetos de acordo com nossas necessidades  e contar com o apoio dos demais.

**Comment by slinstj** [comment]
@ericmaicon, levando em conta sua argumentação sobre namespaces/composer, concordo plenamente. Não tinha pensado nesse ponto-chave.

**Comment by slinstj** [comment]
Resumo:

Este issue definiu que cada membro deverá criar um projeto ou ceder um existente (para melhorias) ao code-on-yii. Uma vez cedido todos os devidos créditos serão dados ao autor porém, se o autor sair da organização, por qualquer motivo, não poderá levar seu projeto consigo novamente (forks são sempre permitidos).
