### ISSUE TITLE
Padrões de codificação

### ISSUE THREAD

**Issue by ericmaicon** [code-on-yii/definicoes#4]
Alguns pontos para discussão:

**Testes**

unitários, funcionais, integração...

**Documentação**

 https://www.phpdoc.org/

**Composer**

http://grossi.io/2013/creating-your-first-composer-packagist-package/
http://culttt.com/2014/05/07/create-psr-4-php-package/

**SemVer**

http://semver.org

**Linguagem**

Português ou Inglês?

**Integração contínua**

https://travis-ci.org/

**PSR**

http://www.php-fig.org/psr/

**Comment by slinstj** [comment]
Composer pra mim é obrigatório. Versionamento pode ser o Semver, já que tenho usado em projetos recentes e acredito que seja o padrão mais usado.

Linguagem também sou a favor do inglês, mesmo para projetos estritamente locais, já que queremos que nosso código seja referência. Vai que um dia precisamos de um trabalho fora do país e o prospectivo empregador queria avaliar nosso trabalho? No entanto, se houver tutoriais além de projetos, voto para que sejam em português, visando a comunidade brasileira (estejam à vontade para discordar e argumentar).

PSR, sim, a 1, a 2 e a 4 deveriam ser as mínimas iniciais. Talvez possamos adotar outras conforme o projeto, já que são mais específicas.

Integração contínua, tenho pouco conhecimento prático, mas sei do alto valor, então também sou a favor.

Testes sim, apenas penso que não precisa ser necessariamente TDD, que não devemos deixar de fazer algo se não pudermos fazer testes antes, ou imediatamente depois, já que os testes podem sim (ao meu ver) ser feitos em outro. Mas entendo deve haver esforço nessa área pela sua importância.

**Comment by ericmaicon** [comment]
Supondo que façamos um widget para Pagseguro. Acho que o desenvolvimento pode ser em inglês (já estou/estamos acostumado), mas pelo menos a primeira doc deveria ser PT, já que é o público principal. 

Sobre o teste, meu grande defeito sempre foi deixar para depois e esquecer o que devia testar (hahaha). Conheço de unit test, já fiz funcional com selenium, mas não sigo nenhuma metodologia ou coisa do tipo. Se alguém tiver XP eu gostaria de ouvir a opinião.

**Comment by almirb** [comment]
Vamos ver...

- Testes: Sei como funciona, mas nunca usei na prática. Boa hora pra aprender;
- Documentação: Ok;
- Composer: Ok;
- Inglês: Ok;
- SemVer: Não conhecia, mas parece simples;
- PSRs: Ok;
- Integração Contínua: Já usei com Delphi, mas nunca com projetos PHP. Mas é algo bom, pois torna o projeto menos suscetível a erros.

**Comment by ericmaicon** [comment]
O lance da integração contínua/testes (principalmente testes) é o tempo. Já que não somos pagos e temos todo o tempo do mundo, não vejo porque não usar.

**Comment by slinstj** [comment]
CI está diretamente amarrada aos testes. Quanto aos testes já fiz testes unitários (via phpunit mesmo) e funcionais (via codeception) no Yii (do funcional para o de aceitação é um pulo). No caso de extensões, provavelmente serão usados mais testes unitários. No caso de widgets, provavelmente serão usados também alguns funcionais, imagino eu.

**Comment by slinstj** [comment]
@almirb legal sua disposição de aprender (testes), acho que todos nós devemos ter essa atitude. Estou à disposição pra te ajudar na questão dos testes e seria legal se pudéssemos fazer o mesmo uns com os outros em várias áreas. Assim nivelamos por cima, não por baixo.

**Comment by slinstj** [comment]
@ericmaicon, sobre docs, geralmente a primeira doc é o README.md e nesse caso teria de ser em inglês também. Mas se te entendi bem, podemos deixar em pt a primeira doc no formato github pages (se houver) já que já teríamos o readme em inglês.

**Comment by ericmaicon** [comment]
Opa, eu tinha pensado no README.md em PT mesmo, pela facilidade de acesso para os users. Mas podemos criar os dois, ou do jeito q vc falou mesmo

**Comment by leandrogehlen** [comment]
Só acho que pra versões poderiamos o usar os proprios `milestones` do github e centralizar em uma unica ferramenta

**Comment by leandrogehlen** [comment]
Acho que os testes não podem ficar pra depois. Sempre que implementar uma funcionalidade o teste já deve ser implentado. 
Sugeri no outro post #5 para utilizar o https://scrutinizer-ci.com/, com isso se os teste não forem implementados o percentual de rotinas cobertas por testes vai baixar

**Comment by leandrogehlen** [comment]
Qunato a documentação, segundo a documentação do yii https://github.com/yiisoft/yii2/blob/master/docs/guide/structure-extensions.md#creating-extensions-, é necessário ter documentação principal em ingles

**Comment by slinstj** [comment]
Certo, então até aqui parece que temos maioria nos itens abaixo:

- Documentação: phpdoc;
- Composer: sempre;
- Inglês: sempre (português, sempre que possível também);
- SemVer: sempre;

**Falta definir:**

- PSRs: sugeri a 1, 2 e 4 mas acho que ninguém mais se pronunciou;
- Testes: minha argumentação de fazer testes mas não ficar travados por causa deles é mais no sentido de sim, vamos fazer sempre que possível, mas não deveriam ser obrigatórios sempre. Acho que vai do bom senso em cada caso. Estou me baseando em meus projetos (onde costumo fazer testes) e neste tópico da documentação do Yii, que achei bem realista, e gostaria que lessem: http://www.yiiframework.com/doc-2.0/guide-test-overview.html#when-and-how-to-test
- CI: pode ser usada sempre, mesmo se não houver muitos testes. Mas só usei uma vez e não lembro qual foi então não tenho argumentos para indicar uma ou outra. Quem já usou pode nos indicar os prós e contras e aí podemos decidir.

**Comment by leandrogehlen** [comment]
@slinstj. Não entendi a questão do ultimo tópico **CI**, por que a função da integração continua é rodar os testes a cada commit.
Eu já utilizei tanto o travis quanto o scrutinizer-ci e também o https://styleci.io/ que acho bem necessário, os testes sempre dão velocidade ao desenvolvimento. 
Em meus projetos sempre tento deixar eles com 90% coberto por testes.

Acho que as 3 ferramentas acima tornam obrigatória uma boa implementação e evita falhas

**Comment by ericmaicon** [comment]
> os testes sempre dão velocidade ao desenvolvimento. 
Infelizmente o povo (donos..) acha o contrário. Mas concordo que no longo prazo reduz muita coisa.

PSRs: acho q rola da gente usar até o phpcs. Concordo com a 1,2 e 4
CI: vamos de scrutinizer e travis. Rola?

**Comment by slinstj** [comment]
@leandrogehlen, foi o que eu disse.

**Comment by slinstj** [comment]
Mas entendo que concorda em não serem obrigatórios (já que citou um percentual abaixo de 100). Não sei se curte muito os testes mas, se sim, acharia viável ser nosso tester primário? Seria interessante pra vc?

**Comment by ericmaicon** [comment]
Opa @slinstj, discordo um pouco disso aí. Acho que o teste tem que ser feito pelo developer que está codificando (se eu entendi o que você falou)

**Comment by slinstj** [comment]
Certo, mas procure ser mais *específico* @ericmaicon. Vou explicar meu ponto de vista novamente: sou *a favor* de testes, mas não a favor de que *tudo*, obrigatoriamente, *deva* ser testado antes de codificar, ou mesmo depois. Estamos falando de exigência mínima. 

No seu caso, você é a favor de **no mínimo** 100% **OU** parcialmente (alguns testes cruciais)? E quanto aos demais membros @code-on-yii/core? 

Votaria por não *exigir* testes simplesmente pq acho que pode travar um pouco nosso time já que alguns não têm (muita) experiência pelo que disseram. No entanto, aceito a opção **parcialmente**, ou seja, haver *no mínimo* testes parciais (os cruciais, centrais, fundamentais). 

Aí vai de votação, mas vamos tentar ser específicos pra comunicação ficar mais objetiva. ;-)

**Comment by slinstj** [comment]
Sobre quem vai fazer, *todos* podem fazer, apenas sugeri ter um tester, alguém que iria fazer (ou talvez ajudar ou cobrar) testes importantes.

**Comment by ericmaicon** [comment]
@slinstj 

sou a favor de 100% de testes, mesmo travando o time. Acho que disse anteriormente, como não temos pressão por tempo nem dinheiro, podemos fazer algo bem feito, mesmo que demore muito. Mas é opinião também, sou a favor das votações que a gente organiza pra ver a opinião do @code-on-yii/core

**Comment by almirb** [comment]
Como nunca trabalhei efetivamente com testes, fica difícil opinar.  Por falta de experiência prática não sei dizer o quanto que os testes oneram o desenvolvimento.

@ericmaicon : você acha viável a cobertura de 100% dos projetos com testes?
@slinstj : que métrica você utilizaria para definir quais as funcionalidades seriam cobertas pelos testes?

**Comment by slinstj** [comment]
Pergunta muito pertinente, @almirb. Porém, não acho que tenha como haver uma "métrica" exatamente. Mas penso em recursos "essenciais" (núcleo, funções vitais) tendo testes e as demais tendo testes *se possível*. 

Testes são um custo de investimento. Retorno não tenho dúvida que trazer. Só não queria travar o desenvolvimento de nossa equipe num primeiro momento. 

Se você não tiver uma posição, temos um empate, já que os demais não estão sendo ativos no time. Nesse caso, voto em cada um decidir em seu projeto. Mas se tivermos que fazer no estilo 100%, tudo bem pra mim também.

**Comment by slinstj** [comment]
Como não houve resposta de sua parte @almirb e estamos empatados vamos deixar que cada um escolha como serão feitos os testes em seus projetos, **porém** vale frisar que devem ser feitos reais esforços de criar testes nos projetos, especialmente os testes de funcionalidades principais.

Fechando o issue.
