### ISSUE TITLE
Nome da organização

### ISSUE THREAD

**Issue by slinstj** [code-on-yii/definicoes#5]
Só pra ficar claro, **depois** que eu criei este nome acabei encontrando outras organizações com nomes muito parecidos (yii-brasil, yiibr, etc).

Acabei achando que talvez pudéssemos diferenciar mais o nome, tal como yii-dev-br. A menos que achem desnecessário ou tenham outras sugestões. 

Se for pra fazer seria ideal agora que ainda não temos projetos porque mudar depois vai invalidar diversos links e criar uma boa dose de dor de cabeça.

**Comment by almirb** [comment]
Yii-Brasil-Dev poderia gerar confusão porque já existe a comunidade Yii-Brasil.

Algumas sugestões:
- Yii-Dev-Br;
- Yii-Team-Brasil;
- Yii-Fw-Br....

**Comment by ericmaicon** [comment]
Naming nunca foi meu forte. Mas podemos fugir do br e do dev tb se quiserem, exemplo:

https://github.com/yii2tech

**Comment by newerton** [comment]
Eu dou preferência ao yii-dev-br, caso haja padronização de outros países que segue o mesmo conceito que o nosso.

**Comment by slinstj** [comment]
Gostei da ideia do @ericmaicon de algo diferente sem br ou dev... acho que vai ser um melhor marketing para o grupo (vide Kartik, como é referencial mesmo sem ser!). Mas aí precisamos ter maioria pra definir isso, dois a dois fica como está.

**Comment by slinstj** [comment]
Até aqui temos:

1. Yii-Dev-Br
2. Yii-Team-Brasil
3. Yii-Fw-Br

Sugiro acrescentar 

4. CodeOn
5. Congruenty

Do dicionário:
congruente = coincidente ou correspondente em características, em propriedades etc.; conforme, concordante, **harmônico**.

**Comment by leandrogehlen** [comment]
Só acho que deve ser

1. yii-dev-br
2. yii-team-brasil
3. yii-fw-br
4. code-on
4. congruenty

Por que o yii é prs-4 todos os namespace sao minusculos

**Comment by ericmaicon** [comment]
opa, bem lembrado sobre os namespace.

Outra coisa, estou esperando sair o nome para criar o grupo no slack com o mesmo nome.

**Comment by slinstj** [comment]
Blz, mas o nome do grupo não interfere no namespace, poderiam até ser diferentes de fosse preciso.
Vocês só estão esquecendo de votar numa opção ou sugerir uma nova. 
Eu ainda não achei que sejam bons nomes, mas até aqui voto no congruenty.

**Comment by newerton** [comment]
@leandrogehlen eu ia comentar sobre ser minusculo, por causa dos namespace.

Meu voto vai pro **yii-dev-br** ou **code-on**.

**Comment by ericmaicon** [comment]
Gostei do **code-on**.

**Comment by slinstj** [comment]
Então fechamos em `code-on` por maioria de votos. Ótimo, pois temos de sair logo dessas definições básicas.

Muito bom pessoal!

**Comment by slinstj** [comment]
Votação da maioria:

- `code-on`: [eric, leandro, newerton];

**Comment by ericmaicon** [comment]
Vai criar outra organization e fechar essa? tem como renomear? Eu sou a favor de usar o mesmo nome nos namespace tb (divulgação).

**Comment by almirb** [comment]
Sei que agora é tarde, mas tb achei `code-on` legal. :)

**Comment by slinstj** [comment]
Tem como renomear sim. Dei uma pesquisada no celular ontem no google e não tinha niguém com nome exatamente igual, mas hoje, pesquisando no github, parece que há outros. Então vou tentar renomear agora, mas se não der, reabro este tópico para criarmos uma variação (tipo codeon5, etc) ou mesmo outro nome.

Sim, também acho que devemos sim usar o padrão no namespace.

**Comment by slinstj** [comment]
Galera, falha minha! Ontem não sei como pesquisei (fiz alguma inhaca) e não achei ninguém com codeon, mas já existe sim. E code-on também. O que está disponível é `codeon5`. Aceitam? @Yii-Brasil-Dev/core

**Comment by ericmaicon** [comment]
Criei no slack code-on-yii, mas foi pq já existia o outro também. Podemos renomear.

**Comment by slinstj** [comment]
Ficou show mas daria uma amarrada ao Yii. Pensei que talvez venhamos a fazer algo em php puro em algum momento (visando aprendizagem e colaboração com a comunidade) e aí fugiria um pouco, mas vai da votação (droga, de novo! rsss)

**Comment by almirb** [comment]
Por mim poderia ser code-on-yii.

**Comment by newerton** [comment]
Se estamos usando o code-on, ao meu ponto de vista, seria melhor o code-on-yii, quem sabe futuramente podemos desenvolver em outras linguagem/ferramentas, como code-on-angular, code-on-ionic, code-on-(ferramenta).

**Comment by slinstj** [comment]
Blz, então fechamos novamente. Vou renomear a org pra `code-on-yii`. Não se esqueçam de atualizar seus links pq muda tudo...
