### ISSUE TITLE
Relacionamento do grupo

### ISSUE THREAD

**Issue by slinstj** [code-on-yii/definicoes#6]
Seria bom ter algumas regras básicas para reduzir/amenizar atritos no grupo (que é algo inevitável). Tenho algumas sugestões que acho básicas:

Regra 1: *NUNCA* se ofenda se for corrigido e saiba ceder;
Regra 2: *NUNCA* seja ofensivo se for corrigir e saiba ceder;
Regra 3: *NIVELAMENTO*: Aprenda com quem sabe mais e ensine quem sabe menos;
Regra 4: *CUMPRA* o que se comprometeu a fazer e evite desculpas;
Regra 5: Seja *SEMPRE* educado, esforçado e se possível, bem-humorado;

Acho que pode ser útil ter esses pontos em mente.

**Comment by almirb** [comment]
Por mim está ótimo.
