### ISSUE TITLE
Mensurando membros

### ISSUE THREAD

**Issue by slinstj** [code-on-yii/definicoes#7]
Galera, gostaria de ideias sobre como poderíamos mensurar a participação de cada membro e sobre como podemos evitar que membros sejam inativos (ou devagar quase parando!).

Pensei nas seguintes possibilidades iniciais:

1. Todos os membros, até o dia 15/06/16, DEVEM possuir pelo menos um projeto na organização;
2. Todos os membros DEVEM participar no mínimo *quinzenalmente* em qualquer projeto (participar = codificar, documentar, traduzir, testar, implementar, corrigir, etc) (issues não contam);
3. Todos os membros DEVEM participar *semanalmente* em pelo menos 20% das issues de projetos dos colegas e em pelo menos 70% das issues de seus próprios projetos (aqui, participar = opinar, sugerir, questionar, corrigir, etc);

Se qualquer das situações acima não for cumprida, haverá *notificação* por e-mail ao membro (c/c aos demais). Havendo *reincidência* em até 90 dias, o membro será transformado em membro externo e somente sob aprovação dos demais poderá retornar ao grupo principal (ou ser removido de vez após 30 dias sem atividades como membro externo).

Mas como eu disse, são ideias iniciais, preciso da opinião se vocês pois não estou totalmente confortável. Muito exigente? Muito liberal? Muito radical? Outras possibilidades?

O foco é: para ser referência, o grupo não pode parar.

**Comment by slinstj** [comment]
@code-on-yii/core ?

**Comment by ericmaicon** [comment]
teste

**Comment by ericmaicon** [comment]
Acho quinzenalmente muito, já que não temos aqui como o compromisso principal. Pode ser mensal. Acho que o mesmo vale pro "semanalmente".

O resto pra mim tá tranquilo.

**Comment by slinstj** [comment]
Um commit por mês acho muito pouco! O meio termo seria um commit a cada 3 semanas, pelo menos (embora ainda acho extremamente pouco). Podíamos começar assim e depois voltar e alterar se todos virem a necessidade. Que tal?

**Comment by almirb** [comment]
Por mim poderia ser 3 semanas em caráter de teste.  Temos que ver como o barco vai andar para ir ajustando esses parâmetros.  Concordo com as outras definições.

**Comment by slinstj** [comment]
Tudo bem pra você também @ericmaicon ??

**Comment by slinstj** [comment]
Como não houve resposta de sua parte @ericmaicon, estou supondo que tudo bem e fechando o issue.

A regra 2 foi alterada para três semanas.
